### ISSUE TITLE
Add support for Noark 5 Versjon 4.0 schemas

### ISSUE THREAD

**Issue by solfeggietto** [documaster/noark-extraction-validator#26]
Arkivverket have now released schemas for Noark 5 Versjon 4.0

This a new parameter must be added for Noark 5 Versjon 4.0:
noark540

This in addition to existing schemas Noark 5 Versjon 3.1
noark 53

**Comment by solfeggietto** [comment]
The new schemas for Noark 5 Version 4.0 have failed to include optional values for M619 avskrivningsmaate in metadatakalog.xsd. I will send a follow-up on this issue to Arkivverket, as this is one of the main issues we filed in the first place.

<xs:simpleType name="avskrivningsmaate">
    <xs:annotation>
      <xs:documentation>M619</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Besvart med brev"/>
      <xs:enumeration value="Besvart med e-post"/>
      <xs:enumeration value="Besvart på telefon"/>
      <xs:enumeration value="Tatt til etterretning"/>
      <xs:enumeration value="Tatt til orientering"/>
    </xs:restriction>
  </xs:simpleType>

**Comment by ivaylomitrev** [comment]
The feature was added in release 0.3.0. I will close the issue for now.

Note that support for Noark 5.5 has also been added in a subsequent release.
