### ISSUE TITLE
Why depend on dh-systemd for Debian build?

### ISSUE THREAD

**Issue by petterreinholdtsen** [documaster/noark-extraction-validator#42]
The debian build rules depend on dh-systemd, but I fail to figure out why.  Is it no longer needed?  It also depend on dh-exec, and I fail to find anywhere it is used too.  Perhaps time to remove it, and simplify debian/rules to only include this:

```
#!/usr/bin/make -f
%:
        dh $@
```

**Comment by ivaylomitrev** [comment]
You are correct. We will address the changes.

**Comment by IvanPenevDocumaster** [comment]
This issue is resolved in the feature/MIGTOOL-89-remove-unnecessary-deb-package-configuration branch which is merged in develop.
