### ISSUE TITLE
Fix high memory usage when generating Excel reports

### ISSUE THREAD

**Issue by douzounov** [documaster/noark-extraction-validator#51]
When validating large extraction packages with the setting for generating an Excel report, the validator uses a lot of memory. This must be investigated and memory usage improved.

**Comment by IvanPenevDocumaster** [comment]
When using the application it is strongly recommended to always limit the Java heap space (in other words how much maximum RAM the application is allowed to consume) via the '-Xmx123MB' flag (note that 123MB is just an example number - it has to be replaced with the according value). Also if earlier than 'Java 9' version is used please consider adding the '-XX:+UseG1GC' flag (uses a more memory and CPU efficient garbage collector).
The code changes include:
1. Support for a 'file' database (the default one is 'in-memory') - this is done by specifying '-storage HSQLDB_FILE' as an argument
2. Report generation for EXCEL_XLS is improved - the application now writes the report in chunks, by 'streaming' its contents into the file (previously it loaded everything in the memory and then wrote it to the file). There is a backwards compatibility in case of unforeseen issues with this new type of report generation: just add '-old-xlsx-report-generation' to the command arguments and the app will write the report the same way it previously did.

This issue will be resolved in https://github.com/documaster/noark-extraction-validator/pull/52 .
